In [5]:
import scipy.io as sio
import os
import wget
import numpy as np
import pandas as pd
import shutil
# import io
import string
import re
import math
import struct

# Download and Preporcess ZUGO Files

In [ ]:
wget.download('https://files.osf.io/v1/resources/q3zws/providers/osfstorage/5afd6aa3ee2b5f000d45028e?action=download&direct&version=2',
              'resultsZAB_SR.mat')
wget.download('https://files.osf.io/v1/resources/q3zws/providers/osfstorage/5afd6c17ee2b5f000f44d94e?action=download&direct&version=2',
              'resultsZDM_SR.mat')
wget.download('https://files.osf.io/v1/resources/q3zws/providers/osfstorage/5afd6a39ee2b5f000f44d824?action=download&direct&version=3',
              'resultsZDN_SR.mat')
wget.download('https://files.osf.io/v1/resources/q3zws/providers/osfstorage/5afd6b96ee2b5f000e44ce1e?action=download&direct&version=2',
              'resultsZGW_SR.mat')
wget.download('https://files.osf.io/v1/resources/q3zws/providers/osfstorage/5afd6bd393d197000f2f2903?action=download&direct&version=2',
              'resultsZJM_SR.mat')
wget.download('https://files.osf.io/v1/resources/q3zws/providers/osfstorage/5afd6c3fee2b5f000d4503ef?action=download&direct&version=2',
              'resultsZJN_SR.mat')
wget.download('https://files.osf.io/v1/resources/q3zws/providers/osfstorage/5afd6a8f93d197000e2efec6?action=download&direct&version=2',
              'resultsZJS_SR.mat')
wget.download('https://files.osf.io/v1/resources/q3zws/providers/osfstorage/5afd6bd793d197000f2f2907?action=download&direct&version=2',
              'resultsZKB_SR.mat')
wget.download('https://files.osf.io/v1/resources/q3zws/providers/osfstorage/5afd6abe93d197000f2f280d?action=download&direct&version=2',
              'resultsZKH_SR.mat')
wget.download('https://files.osf.io/v1/resources/q3zws/providers/osfstorage/5afd6beeee2b5f001044ca15?action=download&direct&version=2',
              'resultsZKW_SR.mat')
wget.download('https://files.osf.io/v1/resources/q3zws/providers/osfstorage/5afd6b9593d197000e2eff90?action=download&direct&version=2',
              'resultsZMG_SR.mat')
wget.download('https://files.osf.io/v1/resources/q3zws/providers/osfstorage/5afd6a9f93d197000e2efed0?action=download&direct&version=2',
              'resultsZPH_SR.mat')


'resultsZPH_SR.mat'

In [ ]:
file_list = []
for i in os.listdir():
    if i.find('results') != -1:
        print(i)
        file_list.append(i)

resultsZJN_SR.mat
resultsZDN_SR.mat
resultsZJM_SR.mat
resultsZKW_SR.mat
resultsZMG_SR.mat
resultsZKH_SR.mat
resultsZGW_SR.mat
resultsZKB_SR.mat
resultsZDM_SR.mat
resultsZJS_SR.mat
resultsZAB_SR.mat
resultsZPH_SR.mat


In [ ]:
### HOW TO READ MATLAB FILE IN PYTHON 3 ###

# set correct file name
file_name = "./resultsZDM_SR.mat"

# index of the array `data` is the number of sentence
data = sio.loadmat(file_name, squeeze_me=True, struct_as_record=False)['sentenceData']

# get all field names for sentence data
print(data[0]._fieldnames)

# example: print sentence
print(data[0].content)



['content', 'rawData', 'mean_t1', 'mean_t2', 'mean_a1', 'mean_a2', 'mean_b1', 'mean_b2', 'mean_g1', 'mean_g2', 'mean_t1_sec', 'mean_t2_sec', 'mean_a1_sec', 'mean_a2_sec', 'mean_b1_sec', 'mean_b2_sec', 'mean_g1_sec', 'mean_g2_sec', 'mean_t1_diff', 'mean_t2_diff', 'mean_a1_diff', 'mean_a2_diff', 'mean_b1_diff', 'mean_b2_diff', 'mean_g1_diff', 'mean_g2_diff', 'mean_t1_diff_sec', 'mean_t2_diff_sec', 'mean_a1_diff_sec', 'mean_a2_diff_sec', 'mean_b1_diff_sec', 'mean_b2_diff_sec', 'mean_g1_diff_sec', 'mean_g2_diff_sec', 'word', 'omissionRate', 'allFixations', 'wordbounds', 'answer_mean_t1', 'answer_mean_t2', 'answer_mean_a1', 'answer_mean_a2', 'answer_mean_b1', 'answer_mean_b2', 'answer_mean_g1', 'answer_mean_g2', 'answer_mean_t1_diff', 'answer_mean_t2_diff', 'answer_mean_a1_diff', 'answer_mean_a2_diff', 'answer_mean_b1_diff', 'answer_mean_b2_diff', 'answer_mean_g1_diff', 'answer_mean_g2_diff']
Presents a good case while failing to provide a reason for us to care beyond the very basic dictums

In [ ]:
zuco_text = np.array([data[i].content for i in range(len(data))])
np.save('data/zuco_text.npy', zuco_text)

In [ ]:
def clean_document(document):
    document = document.lower()
    table = str.maketrans({key: None for key in string.punctuation})
    cleaned_document = document.translate(table)  
    return cleaned_document

In [ ]:
zuco_text = np.load('data/zuco_text.npy')

In [ ]:
cleaned_reviews = [clean_document(doc) for doc in zuco_text]
zuco_new_text = np.array(cleaned_reviews)

In [ ]:
print(zuco_new_text[0])

presents a good case while failing to provide a reason for us to care beyond the very basic dictums of human decency


In [ ]:
np.save('data/zuco_new_text.npy', zuco_new_text)

In [ ]:
len_list = [data[i].word.shape[0] for i in range(len(data))]
print('Average sentence length: %s'%np.mean(len_list))

Average sentence length: 17.8225


In [ ]:
# example: get omission rate of first sentence
omission_rate = data[0].omissionRate
print(omission_rate)

# get word level data
word_data = data[0].word

# get names of all word features
# index of the array `word_data` is the number of the word
print(word_data[0]._fieldnames)

0.22727272727272727
['content', 'fixPositions', 'nFixations', 'meanPupilSize', 'rawEEG', 'rawET', 'FFD', 'FFD_pupilsize', 'FFD_t1', 'FFD_t2', 'FFD_a1', 'FFD_a2', 'FFD_b1', 'FFD_b2', 'FFD_g1', 'FFD_g2', 'FFD_t1_diff', 'FFD_t2_diff', 'FFD_a1_diff', 'FFD_a2_diff', 'FFD_b1_diff', 'FFD_b2_diff', 'FFD_g1_diff', 'FFD_g2_diff', 'TRT', 'TRT_pupilsize', 'TRT_t1', 'TRT_t2', 'TRT_a1', 'TRT_a2', 'TRT_b1', 'TRT_b2', 'TRT_g1', 'TRT_g2', 'TRT_t1_diff', 'TRT_t2_diff', 'TRT_a1_diff', 'TRT_a2_diff', 'TRT_b1_diff', 'TRT_b2_diff', 'TRT_g1_diff', 'TRT_g2_diff', 'GD', 'GD_pupilsize', 'GD_t1', 'GD_t2', 'GD_a1', 'GD_a2', 'GD_b1', 'GD_b2', 'GD_g1', 'GD_g2', 'GD_t1_diff', 'GD_t2_diff', 'GD_a1_diff', 'GD_a2_diff', 'GD_b1_diff', 'GD_b2_diff', 'GD_g1_diff', 'GD_g2_diff', 'GPT', 'GPT_pupilsize', 'GPT_t1', 'GPT_t2', 'GPT_a1', 'GPT_a2', 'GPT_b1', 'GPT_b2', 'GPT_g1', 'GPT_g2', 'GPT_t1_diff', 'GPT_t2_diff', 'GPT_a1_diff', 'GPT_a2_diff', 'GPT_b1_diff', 'GPT_b2_diff', 'GPT_g1_diff', 'GPT_g2_diff', 'SFD', 'SFD_pupilsize', 

In [ ]:
# example: get first word
print(word_data[0].content)

# example: get number of fixations of first word
print(word_data[0].nFixations)
print(word_data[1].nFixations)

# example: get total reading time
print(word_data[0].TRT)
print(word_data[1].TRT)

# get MEAN FIX DUR of first word
print(word_data[0].TRT/word_data[0].nFixations)

Presents
4
3
669
295
167.25


In [ ]:
word_data_list = [data[i].word for i in range(len(data))]

In [ ]:
max_len = max([len(word_data_list[i]) for i in range(len(word_data_list))])
print(max_len)

43


In [ ]:
mfd_big_array_list = []
for file_name in file_list:
    data = sio.loadmat(file_name, squeeze_me=True, struct_as_record=False)['sentenceData']
    word_data_list = [data[i].word for i in range(len(data))]
    mfd_big_list = []
    for word_data in word_data_list:
        mfd_list = []
        if type(word_data) is float:
            mfd_list = [np.nan] * 43
        else:
            word_data_len = len(word_data)
            for wi in range(word_data_len):
                if type(word_data[wi].TRT) is not int:
                    mfd = 0.0
                else:
                    mfd = word_data[wi].TRT/word_data[wi].nFixations
                mfd_list.append(mfd)
            if word_data_len < 43:
                mfd_list += [0.0] * (43 - len(mfd_list))
        mfd_big_list.append(mfd_list)
    mfd_big_array = np.asarray(mfd_big_list)
    mfd_big_array_list.append(mfd_big_array)

In [ ]:
mfd_array = np.nanmean(np.asarray(mfd_big_array_list), axis=0)
np.save('data/mfd_scores.npy', mfd_array)

# Convert to Glove Embeddings

In [ ]:
zuco_new_text = np.load('data/zuco_new_text.npy')
mfd_scores = np.load('data/mfd_scores.npy')

In [ ]:
embeddings_index = dict()
with open('glove.6B.100d.txt') as f:
    for line in f:
        values = line.split()
        word = values[0]
        coefs = np.asarray(values[1:], dtype='float32')
        embeddings_index[word] = coefs

In [ ]:
max_words = 73 #num_words

output_zuco = []
for review in zuco_new_text:
    words = review.split()
    words_mapped = [0]* max_words
    
    length = len(words)
    if(length<max_words):
        #print('We should never see this print')
        for i in range(0,length):
            words_mapped[i] = embeddings_index.get(words[i], embeddings_index['unk'])
        for i in range(length,max_words):
            words_mapped[i] =  embeddings_index['unk']
    elif (length>max_words):
        print('We should never see this print either')
    else:
        for i in range(0,max_words):
            words_mapped[i] = embeddings_index.get(words[i], embeddings_index['unk'])
            
    output_zuco.append(words_mapped)
    
output_zuco = np.array(output_zuco)
print(output_zuco.shape)
print(output_zuco[0])

(400, 73, 100)
[[-0.49862   0.28541   0.35966  ... -0.48704   0.78987   0.7194  ]
 [-0.27086   0.044006 -0.02026  ... -0.4923    0.63687   0.23642 ]
 [-0.030769  0.11993   0.53909  ... -0.52878   0.17584   1.065   ]
 ...
 [ 0.027166 -0.1762   -0.19623  ... -0.37226  -0.28782  -0.015834]
 [ 0.027166 -0.1762   -0.19623  ... -0.37226  -0.28782  -0.015834]
 [ 0.027166 -0.1762   -0.19623  ... -0.37226  -0.28782  -0.015834]]


In [ ]:
np.save('data/zuco_gloves.npy', output_reviews)

# Convert To PubMed Embeddings

In [2]:
from gensim.models.keyedvectors import KeyedVectors
model = KeyedVectors.load_word2vec_format('medical_data/PubMed-w2v.bin', binary=True)

/usr/local/lib/python3.6/dist-packages/smart_open/smart_open_lib.py:254: UserWarning: This function is deprecated, use smart_open.open instead. See the migration notes for details: https://github.com/RaRe-Technologies/smart_open/blob/master/README.rst#migrating-to-the-new-open-function
  'See the migration notes for details: %s' % _MIGRATION_NOTES_URL


In [6]:
zuco_new_text = np.load('data/zuco_new_text.npy')
mfd_scores = np.load('data/mfd_scores.npy')

In [7]:
cleaned_reviews = [zuco_new_text[i].split() for i in range(len(zuco_new_text))]
baseline_att = mfd_scores

In [8]:
max_words = 43 #num_words
num_unk = 0
num_normal = 0 
output_reviews = []
att_labels =[]

for words,attscr in zip(cleaned_reviews, baseline_att):
    words_mapped = [0]* max_words
    att_mapped =[0]* max_words
    length = len(words)
    if(length<max_words):
        for i in range(0,length):
            att_mapped[i] = attscr[i]
            try:
                words_mapped[i] = model[words[i]]
                num_normal += 1
            except:
                words_mapped[i] = model['unk']
                num_unk += 1
        for i in range(length,max_words):
            words_mapped[i] =  model['unk']
            att_mapped[i] = 0
    else:
        for i in range(0,max_words):
            att_mapped[i] = attscr[i]
            try:
                words_mapped[i] = model[words[i]]
                num_normal += 1
            except:
                words_mapped[i] = model['unk']
                num_unk += 1
            
    output_reviews.append(words_mapped)
    att_labels.append(att_mapped)
    
output_reviews  = np.array(output_reviews)
cleaned_reviews = np.array(cleaned_reviews)
att_labels      = np.array(att_labels)

print('num_normal', num_normal)
print('num_unk',num_unk)

print(output_reviews.shape)
print(cleaned_reviews.shape)
print(att_labels.shape)

num_normal 6698
num_unk 376
(400, 43, 200)
(400,)
(400, 43)


In [ ]:
np.save('medical_data/zuco_pubmed.npy', output_reviews)
np.save('medical_data/zuco_pubmed_att_labels.npy', att_labels)